### ISSUE TITLE
Yarn support and/or callback

### ISSUE THREAD

**Issue by taoeffect** [mgol/grunt-check-dependencies#14]
Currently this package doesn't support [Yarn](https://yarnpkg.com/). This could be ameliorated either by:

- Adding support for Yarn
- Or, adding semi-generic support for package managers that come along (that support the package.json format, like Yarn does). This could be done by offering in the options to specify a callback function that's called if the dependencies are out of date. In there I could manually run Yarn or whatever else.

**Comment by mgol** [comment]
I'm good with both solutions; the second one is more generic but I see yarn is gaining enough traction that the library may as well support it natively.

Would you like to prepare a PR? I can help if you don't understand something around a codebase.

**Comment by mgol** [comment]
Note, though, that Yarn is so quick when run on an already setup project that it might be simpler to just always invoke `yarn` at the beginning of your Gruntfile. :-)

**Comment by mgol** [comment]
This feature would have to be added at https://github.com/mgol/check-dependencies/ as this is just its Grunt task so please re-create the issue there. Thanks.
